### ISSUE TITLE
Deliveries: unexpected channel close

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search#233]
ipfs-search-ipfs-crawler-1  | panic: unexpected channel close [recovered]
ipfs-search-ipfs-crawler-1  | 	panic: unexpected channel close
ipfs-search-ipfs-crawler-1  | 
ipfs-search-ipfs-crawler-1  | goroutine 259 [running]:
ipfs-search-ipfs-crawler-1  | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
ipfs-search-ipfs-crawler-1  | 	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:393 +0x48
ipfs-search-ipfs-crawler-1  | go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000340480, {0x0, 0x0, 0xc0040df8e0?})
ipfs-search-ipfs-crawler-1  | 	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:432 +0xa9a
ipfs-search-ipfs-crawler-1  | panic({0x137d6e0, 0x1836d10})
ipfs-search-ipfs-crawler-1  | 	/usr/local/go/src/runtime/panic.go:890 +0x262
ipfs-search-ipfs-crawler-1  | github.com/ipfs-search/ipfs-search/components/worker.(*Worker).Start(0xc000118640, {0x183def0, 0xc000099a10}, 0xc00012c300)
ipfs-search-ipfs-crawler-1  | 	/src/components/worker/worker.go:44 +0x45f
ipfs-search-ipfs-crawler-1  | created by github.com/ipfs-search/ipfs-search/components/worker/pool.(*Pool).startWorkers
ipfs-search-ipfs-crawler-1  | 	/src/components/worker/pool/pool.go:42 +0x16c

**Comment by dokterbob** [comment]
Idea: allow errors to bubble from workers through an error group, perform soft restart when any one fails.
Risk memory leaks though.

https://pkg.go.dev/golang.org/x/sync/errgroup

Long term objective: get rid of RabbitMQ and replace by ZeroMQ/Kafka/nsqd/...
